language: node_js
node_js:
    - 10.15
before_install:
  - npm i -g npm@6.4.1
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.32
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
