version: "3"
services:
  postgres_database:
    image: postgres:10-alpine
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
      POSTGRES_DB: devDB
    ports:
      - 5433:5432
  
  server:
    build: .
    ports:
      - 3000:3000
    links:
      - postgres_database
    depends_on:
      - postgres_database
    command: >
      /bin/bash -c "
        while ! nc -z postgres_database 5432;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
        yarn run start;
      "

  

